/* THIS FILE IS AUTOMATICALLY GENERATED */
/* RUN rake generate_ts_routes TO UPDATE THE ROUTES BELOW */

/* tslint:disable */
/* This is generated by ts_routes-rails */

export type ScalarType = string | number | boolean;

function $buildOptions(options: any, names: string[]): string {
  if (options) {
    let anchor = "";
    const q = [] as string[];
    for (const key of Object.keys(options)) {
      if (names.indexOf(key) !== -1) {
        // the key is already consumed
        continue;
      }

      const value = options[key];

      if (key === "anchor") {
        anchor = `#${$encode(value)}`;
      } else {
        $buildQuery(q, key, value);
      }
    }
    return (q.length > 0 ? "?" + q.join("&") : "") + anchor;
  } else {
    return "";
  }
}

function $buildQuery(q: string[], key: string, value: any) {
  if ($isScalarType(value)) {
    q.push(`${$encode(key)}=${$encode(value)}`);
  } else if (Array.isArray(value)) {
    for (const v of value) {
      $buildQuery(q, `${key}[]`, v);
    }
  } else if (value != null) {
    // i.e. non-null, non-scalar, non-array type
    for (const k of Object.keys(value)) {
      $buildQuery(q, `${key}[${k}]`, value[k]);
    }
  }
}

function $encode(value: any): string {
  return encodeURIComponent(value);
}

function $isScalarType(value: any): value is ScalarType {
  return (
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  );
}

function $isPresent(value: any): boolean {
  return value != null && ("" + value).length > 0;
}

function $hasPresentOwnProperty(options: any, key: string): boolean {
  return options && options.hasOwnProperty(key) && $isPresent(options[key]);
}

/** /rails/info/properties(.:format) */
export function rails_info_properties_path(options?: object): string {
  return "/" + "rails" + "/" + "info" + "/" + "properties" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/info/routes(.:format) */
export function rails_info_routes_path(options?: object): string {
  return "/" + "rails" + "/" + "info" + "/" + "routes" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/info(.:format) */
export function rails_info_path(options?: object): string {
  return "/" + "rails" + "/" + "info" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/mailers(.:format) */
export function rails_mailers_path(options?: object): string {
  return "/" + "rails" + "/" + "mailers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /graphiql */
export function graphiql_rails_path(options?: object): string {
  return "/" + "graphiql" + $buildOptions(options, []);
}

/** /graphql(.:format) */
export function graphql_path(options?: object): string {
  return "/" + "graphql" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /graphql_jwt(.:format) */
export function graphql_jwt_path(options?: object): string {
  return "/" + "graphql_jwt" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /graphql_dev(.:format) */
export function graphql_dev_path(options?: object): string {
  return "/" + "graphql_dev" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /super_admin */
export function rails_admin_path(options?: object): string {
  return "/" + "super_admin" + $buildOptions(options, []);
}

/** /super_admin/ */
export function rails_admin_dashboard_path(options?: object): string {
  return "/" + "super_admin" + "/" + $buildOptions(options, []);
}

/** /super_admin/:model_name(.:format) */
export function rails_admin_index_path(model_name: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","format"]);
}

/** /super_admin/:model_name/new(.:format) */
export function rails_admin_new_path(model_name: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","format"]);
}

/** /super_admin/:model_name/export(.:format) */
export function rails_admin_export_path(model_name: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + "/" + "export" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","format"]);
}

/** /super_admin/:model_name/bulk_action(.:format) */
export function rails_admin_bulk_action_path(model_name: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + "/" + "bulk_action" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","format"]);
}

/** /super_admin/:model_name/:id(.:format) */
export function rails_admin_show_path(model_name: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","id","format"]);
}

/** /super_admin/:model_name/:id/edit(.:format) */
export function rails_admin_edit_path(model_name: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","id","format"]);
}

/** /super_admin/:model_name/:id/show_in_app(.:format) */
export function rails_admin_show_in_app_path(model_name: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + "/" + id + "/" + "show_in_app" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","id","format"]);
}

/** /super_admin/:model_name/:id/delete(.:format) */
export function rails_admin_delete_path(model_name: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "super_admin" + "/" + model_name + "/" + id + "/" + "delete" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["model_name","id","format"]);
}

/** /field_providers(.:format) */
export function field_providers_path(options?: object): string {
  return "/" + "field_providers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field_providers/new(.:format) */
export function new_field_provider_path(options?: object): string {
  return "/" + "field_providers" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field_providers/:id/edit(.:format) */
export function edit_field_provider_path(id: ScalarType, options?: object): string {
  return "/" + "field_providers" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field_providers/:id(.:format) */
export function field_provider_path(id: ScalarType, options?: object): string {
  return "/" + "field_providers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admins(.:format) */
export function admins_path(options?: object): string {
  return "/" + "admins" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admins/new(.:format) */
export function new_admin_path(options?: object): string {
  return "/" + "admins" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admins/:id/edit(.:format) */
export function edit_admin_path(id: ScalarType, options?: object): string {
  return "/" + "admins" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admins/:id(.:format) */
export function admin_path(id: ScalarType, options?: object): string {
  return "/" + "admins" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin_notes(.:format) */
export function admin_notes_path(options?: object): string {
  return "/" + "admin_notes" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin_notes/new(.:format) */
export function new_admin_note_path(options?: object): string {
  return "/" + "admin_notes" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin_notes/:id/edit(.:format) */
export function edit_admin_note_path(id: ScalarType, options?: object): string {
  return "/" + "admin_notes" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin_notes/:id(.:format) */
export function admin_note_path(id: ScalarType, options?: object): string {
  return "/" + "admin_notes" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /zones(.:format) */
export function zones_path(options?: object): string {
  return "/" + "zones" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /zones/new(.:format) */
export function new_zone_path(options?: object): string {
  return "/" + "zones" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /zones/:id/edit(.:format) */
export function edit_zone_path(id: ScalarType, options?: object): string {
  return "/" + "zones" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /zones/:id(.:format) */
export function zone_path(id: ScalarType, options?: object): string {
  return "/" + "zones" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /providers(.:format) */
export function providers_path(options?: object): string {
  return "/" + "providers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /providers/new(.:format) */
export function new_provider_path(options?: object): string {
  return "/" + "providers" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /providers/:id/edit(.:format) */
export function edit_provider_path(id: ScalarType, options?: object): string {
  return "/" + "providers" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /providers/:id(.:format) */
export function provider_path(id: ScalarType, options?: object): string {
  return "/" + "providers" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /users/check_session_timeout(.:format) */
export function users_check_session_timeout_path(options?: object): string {
  return "/" + "users" + "/" + "check_session_timeout" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/session_timeout(.:format) */
export function users_session_timeout_path(options?: object): string {
  return "/" + "users" + "/" + "session_timeout" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/sign_out(.:format) */
export function users_sign_out_path(options?: object): string {
  return "/" + "users" + "/" + "sign_out" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/sign_in(.:format) */
export function new_user_session_path(options?: object): string {
  return "/" + "users" + "/" + "sign_in" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/sign_in(.:format) */
export function user_session_path(options?: object): string {
  return "/" + "users" + "/" + "sign_in" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/sign_out(.:format) */
export function destroy_user_session_path(options?: object): string {
  return "/" + "users" + "/" + "sign_out" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/auth/oktaoauth(.:format) */
export function user_oktaoauth_omniauth_authorize_path(options?: object): string {
  return "/" + "users" + "/" + "auth" + "/" + "oktaoauth" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/auth/oktaoauth/callback(.:format) */
export function user_oktaoauth_omniauth_callback_path(options?: object): string {
  return "/" + "users" + "/" + "auth" + "/" + "oktaoauth" + "/" + "callback" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/password/new(.:format) */
export function new_user_password_path(options?: object): string {
  return "/" + "users" + "/" + "password" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/password/edit(.:format) */
export function edit_user_password_path(options?: object): string {
  return "/" + "users" + "/" + "password" + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/password(.:format) */
export function user_password_path(options?: object): string {
  return "/" + "users" + "/" + "password" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/cancel(.:format) */
export function cancel_user_registration_path(options?: object): string {
  return "/" + "users" + "/" + "cancel" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/sign_up(.:format) */
export function new_user_registration_path(options?: object): string {
  return "/" + "users" + "/" + "sign_up" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/edit(.:format) */
export function edit_user_registration_path(options?: object): string {
  return "/" + "users" + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users(.:format) */
export function user_registration_path(options?: object): string {
  return "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/unlock/new(.:format) */
export function new_user_unlock_path(options?: object): string {
  return "/" + "users" + "/" + "unlock" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/unlock(.:format) */
export function user_unlock_path(options?: object): string {
  return "/" + "users" + "/" + "unlock" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /sso_failure(.:format) */
export function sso_failure_path(options?: object): string {
  return "/" + "sso_failure" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /sfdc_scheduler_iframe_demo(.:format) */
export function sfdc_scheduler_iframe_demo_path(options?: object): string {
  return "/" + "sfdc_scheduler_iframe_demo" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /users/invites(.:format) */
export function users_invites_path(options?: object): string {
  return "/" + "users" + "/" + "invites" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tags(.:format) */
export function admin_tags_path(options?: object): string {
  return "/" + "admin" + "/" + "tags" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tags/new(.:format) */
export function new_admin_tag_path(options?: object): string {
  return "/" + "admin" + "/" + "tags" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/tags/:id/edit(.:format) */
export function edit_admin_tag_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tags" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/tags/:id(.:format) */
export function admin_tag_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "tags" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/visits(.:format) */
export function admin_visits_path(options?: object): string {
  return "/" + "admin" + "/" + "visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/visits/calendar(.:format) */
export function admin_visits_calendar_path(options?: object): string {
  return "/" + "admin" + "/" + "visits" + "/" + "calendar" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/visits/map(.:format) */
export function admin_visits_map_path(options?: object): string {
  return "/" + "admin" + "/" + "visits" + "/" + "map" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/background_job_results(.:format) */
export function admin_background_job_results_path(options?: object): string {
  return "/" + "admin" + "/" + "background_job_results" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/polling/patients_worklist/:type(.:format) */
export function admin_patients_worklist_polling_path(type: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "polling" + "/" + "patients_worklist" + "/" + type + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["type","format"]);
}

/** /admin/kustomer/patients/new(.:format) */
export function admin_kustomer_patients_new_path(options?: object): string {
  return "/" + "admin" + "/" + "kustomer" + "/" + "patients" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/kustomer/patients/create(.:format) */
export function admin_kustomer_patients_create_path(options?: object): string {
  return "/" + "admin" + "/" + "kustomer" + "/" + "patients" + "/" + "create" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/alayacare/create(.:format) */
export function admin_alayacare_create_path(options?: object): string {
  return "/" + "admin" + "/" + "alayacare" + "/" + "create" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/alayacare/field_providers(.:format) */
export function admin_alayacare_field_providers_path(options?: object): string {
  return "/" + "admin" + "/" + "alayacare" + "/" + "field_providers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/capacity/availability(.:format) */
export function admin_capacity_availability_path(options?: object): string {
  return "/" + "admin" + "/" + "capacity" + "/" + "availability" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/capacity/get_availability_by_date(.:format) */
export function admin_capacity_get_availability_by_date_path(options?: object): string {
  return "/" + "admin" + "/" + "capacity" + "/" + "get_availability_by_date" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/alayacare/patient_visits_partial(.:format) */
export function admin_alayacare_patient_visits_partial_path(options?: object): string {
  return "/" + "admin" + "/" + "alayacare" + "/" + "patient_visits_partial" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/alayacare/cancel_visit_partial(.:format) */
export function admin_alayacare_cancel_visit_partial_path(options?: object): string {
  return "/" + "admin" + "/" + "alayacare" + "/" + "cancel_visit_partial" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/alayacare/cancel_visit(.:format) */
export function admin_alayacare_cancel_visit_path(options?: object): string {
  return "/" + "admin" + "/" + "alayacare" + "/" + "cancel_visit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/alayacare/edit_visit(.:format) */
export function admin_alayacare_edit_visit_path(options?: object): string {
  return "/" + "admin" + "/" + "alayacare" + "/" + "edit_visit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/alayacare/incoming_event(.:format) */
export function admin_alayacare_incoming_event_path(options?: object): string {
  return "/" + "admin" + "/" + "alayacare" + "/" + "incoming_event" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/appointments/:id/edit_partial(.:format) */
export function edit_partial_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "edit_partial" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments/:id/admin_notes(.:format) */
export function admin_notes_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "admin_notes" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments/:id/tags(.:format) */
export function tags_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "tags" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments/:id/fetch_clinical_summary(.:format) */
export function fetch_clinical_summary_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "fetch_clinical_summary" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments/:id/send_pdf(.:format) */
export function send_pdf_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "send_pdf" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments/:id/visit_results(.:format) */
export function visit_results_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "visit_results" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments/:id/render_visit_summary_pdf(.:format) */
export function render_visit_summary_pdf_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "render_visit_summary_pdf" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments(.:format) */
export function admin_appointments_path(options?: object): string {
  return "/" + "admin" + "/" + "appointments" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/appointments/new(.:format) */
export function new_admin_appointment_path(options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/appointments/:id/edit(.:format) */
export function edit_admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/appointments/:id(.:format) */
export function admin_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "appointments" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:id/admin_notes(.:format) */
export function admin_notes_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "admin_notes" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:id/history(.:format) */
export function history_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "history" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:id/update_status(.:format) */
export function update_status_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "update_status" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:id/alayacare_visit(.:format) */
export function alayacare_visit_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "alayacare_visit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:id/fetch_suggested_visits(.:format) */
export function fetch_suggested_visits_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "fetch_suggested_visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:patient_id/fetch_visit_param_info(.:format) */
export function admin_patient_fetch_visit_param_info_path(patient_id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + patient_id + "/" + "fetch_visit_param_info" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["patient_id","format"]);
}

/** /admin/patients/:id/edit_visit_partial(.:format) */
export function edit_visit_partial_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "edit_visit_partial" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:id/visit_types(.:format) */
export function visit_types_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "visit_types" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:patient_id/visits(.:format) */
export function admin_patient_visits_path(patient_id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + patient_id + "/" + "visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["patient_id","format"]);
}

/** /admin/patients(.:format) */
export function admin_patients_path(options?: object): string {
  return "/" + "admin" + "/" + "patients" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/patients/new(.:format) */
export function new_admin_patient_path(options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/patients/:id/edit(.:format) */
export function edit_admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/patients/:id(.:format) */
export function admin_patient_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patients" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/field_orgs/:id/invite_users(.:format) */
export function invite_users_admin_field_org_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "field_orgs" + "/" + id + "/" + "invite_users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/field_orgs(.:format) */
export function admin_field_orgs_path(options?: object): string {
  return "/" + "admin" + "/" + "field_orgs" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/field_orgs/:id(.:format) */
export function admin_field_org_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "field_orgs" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/demand_partners(.:format) */
export function admin_demand_partners_path(options?: object): string {
  return "/" + "admin" + "/" + "demand_partners" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/demand_partners/:id(.:format) */
export function admin_demand_partner_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "demand_partners" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/:id/edit_partial(.:format) */
export function edit_partial_admin_user_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "edit_partial" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users/invited(.:format) */
export function invited_admin_users_path(options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + "invited" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id/resend_invite(.:format) */
export function resend_invite_admin_user_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + "/" + "resend_invite" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/users(.:format) */
export function admin_users_path(options?: object): string {
  return "/" + "admin" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/users/:id(.:format) */
export function admin_user_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "users" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/field_users/import(.:format) */
export function import_admin_field_users_path(options?: object): string {
  return "/" + "admin" + "/" + "field_users" + "/" + "import" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/field_users/preview_import(.:format) */
export function preview_import_admin_field_users_path(options?: object): string {
  return "/" + "admin" + "/" + "field_users" + "/" + "preview_import" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/field_users/submit_import(.:format) */
export function submit_import_admin_field_users_path(options?: object): string {
  return "/" + "admin" + "/" + "field_users" + "/" + "submit_import" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/hra_surveys(.:format) */
export function admin_hra_surveys_path(options?: object): string {
  return "/" + "admin" + "/" + "hra_surveys" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/patient_prospects(.:format) */
export function admin_patient_prospects_path(options?: object): string {
  return "/" + "admin" + "/" + "patient_prospects" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin/patient_prospects/:id(.:format) */
export function admin_patient_prospect_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "patient_prospects" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/visits/:id(.:format) */
export function admin_visit_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "visits" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/outreach_campaigns/:id/send_one(.:format) */
export function send_one_admin_outreach_campaign_path(id: ScalarType, options?: object): string {
  return "/" + "admin" + "/" + "outreach_campaigns" + "/" + id + "/" + "send_one" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /admin/outreach_campaigns(.:format) */
export function admin_outreach_campaigns_path(options?: object): string {
  return "/" + "admin" + "/" + "outreach_campaigns" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /admin(.:format) */
export function admin_root_path(options?: object): string {
  return "/" + "admin" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field(.:format) */
export function field_root_path(options?: object): string {
  return "/" + "field" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/visits(.:format) */
export function field_visits_path(options?: object): string {
  return "/" + "field" + "/" + "visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/cancel_visit(.:format) */
export function field_cancel_visit_path(options?: object): string {
  return "/" + "field" + "/" + "cancel_visit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/cancel_visit_partial(.:format) */
export function field_cancel_visit_partial_path(options?: object): string {
  return "/" + "field" + "/" + "cancel_visit_partial" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/visits/:id(.:format) */
export function field_visit_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "visits" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/appointments/:appointment_id/hra_surveys(.:format) */
export function field_appointment_hra_surveys_path(appointment_id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "appointments" + "/" + appointment_id + "/" + "hra_surveys" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["appointment_id","format"]);
}

/** /field/appointments/:appointment_id/hra_surveys/new(.:format) */
export function new_field_appointment_hra_survey_path(appointment_id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "appointments" + "/" + appointment_id + "/" + "hra_surveys" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["appointment_id","format"]);
}

/** /field/appointments/:appointment_id/surveys/:id/respond(.:format) */
export function respond_field_appointment_survey_path(appointment_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "appointments" + "/" + appointment_id + "/" + "surveys" + "/" + id + "/" + "respond" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["appointment_id","id","format"]);
}

/** /field/appointments/:appointment_id/surveys/:id(.:format) */
export function field_appointment_survey_path(appointment_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "appointments" + "/" + appointment_id + "/" + "surveys" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["appointment_id","id","format"]);
}

/** /field/appointments/:appointment_id/extra_vaccine_recipients/:id/edit(.:format) */
export function edit_field_appointment_extra_vaccine_recipient_path(appointment_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "appointments" + "/" + appointment_id + "/" + "extra_vaccine_recipients" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["appointment_id","id","format"]);
}

/** /field/appointments/:appointment_id/extra_vaccine_recipients/:id(.:format) */
export function field_appointment_extra_vaccine_recipient_path(appointment_id: ScalarType, id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "appointments" + "/" + appointment_id + "/" + "extra_vaccine_recipients" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["appointment_id","id","format"]);
}

/** /field/appointments(.:format) */
export function field_appointments_path(options?: object): string {
  return "/" + "field" + "/" + "appointments" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/appointments/:id(.:format) */
export function field_appointment_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "appointments" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:id/admin_notes(.:format) */
export function admin_notes_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "admin_notes" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:id/history(.:format) */
export function history_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "history" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:id/update_status(.:format) */
export function update_status_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "update_status" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:id/alayacare_visit(.:format) */
export function alayacare_visit_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "alayacare_visit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:id/fetch_suggested_visits(.:format) */
export function fetch_suggested_visits_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "fetch_suggested_visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:patient_id/fetch_visit_param_info(.:format) */
export function field_patient_fetch_visit_param_info_path(patient_id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + patient_id + "/" + "fetch_visit_param_info" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["patient_id","format"]);
}

/** /field/patients/:id/edit_visit_partial(.:format) */
export function edit_visit_partial_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "edit_visit_partial" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:id/visit_types(.:format) */
export function visit_types_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "visit_types" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:patient_id/visits(.:format) */
export function field_patient_visits_path(patient_id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + patient_id + "/" + "visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["patient_id","format"]);
}

/** /field/patients(.:format) */
export function field_patients_path(options?: object): string {
  return "/" + "field" + "/" + "patients" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/patients/new(.:format) */
export function new_field_patient_path(options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/patients/:id/edit(.:format) */
export function edit_field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/patients/:id(.:format) */
export function field_patient_path(id: ScalarType, options?: object): string {
  return "/" + "field" + "/" + "patients" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /field/capacity/availability(.:format) */
export function field_capacity_availability_path(options?: object): string {
  return "/" + "field" + "/" + "capacity" + "/" + "availability" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /field/capacity/get_availability_by_date(.:format) */
export function field_capacity_get_availability_by_date_path(options?: object): string {
  return "/" + "field" + "/" + "capacity" + "/" + "get_availability_by_date" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /dashboard/field_admin(.:format) */
export function dashboard_field_admin_root_path(options?: object): string {
  return "/" + "dashboard" + "/" + "field_admin" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /dashboard/field_admin/users/office_users(.:format) */
export function office_users_dashboard_field_admin_users_path(options?: object): string {
  return "/" + "dashboard" + "/" + "field_admin" + "/" + "users" + "/" + "office_users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /dashboard/field_admin/users/field_providers(.:format) */
export function field_providers_dashboard_field_admin_users_path(options?: object): string {
  return "/" + "dashboard" + "/" + "field_admin" + "/" + "users" + "/" + "field_providers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /dashboard/field_admin/users/:id/resend_invite(.:format) */
export function resend_invite_dashboard_field_admin_user_path(id: ScalarType, options?: object): string {
  return "/" + "dashboard" + "/" + "field_admin" + "/" + "users" + "/" + id + "/" + "resend_invite" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /dashboard/field_admin/users(.:format) */
export function dashboard_field_admin_users_path(options?: object): string {
  return "/" + "dashboard" + "/" + "field_admin" + "/" + "users" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /dashboard/field_admin/users/new(.:format) */
export function new_dashboard_field_admin_user_path(options?: object): string {
  return "/" + "dashboard" + "/" + "field_admin" + "/" + "users" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /data_import/new_data_import(.:format) */
export function data_import_new_data_import_path(options?: object): string {
  return "/" + "data_import" + "/" + "new_data_import" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /data_import/data_import(.:format) */
export function data_import_data_import_path(options?: object): string {
  return "/" + "data_import" + "/" + "data_import" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /visit_routing/new_visit(.:format) */
export function visit_routing_new_visit_path(options?: object): string {
  return "/" + "visit_routing" + "/" + "new_visit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /visit_routing/get_options(.:format) */
export function visit_routing_get_options_path(options?: object): string {
  return "/" + "visit_routing" + "/" + "get_options" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/index(.:format) */
export function alayacare_control_panel_index_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "index" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/sync_demand_partner_ids(.:format) */
export function alayacare_control_panel_sync_demand_partner_ids_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "sync_demand_partner_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/sync_cancel_code_ids(.:format) */
export function alayacare_control_panel_sync_cancel_code_ids_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "sync_cancel_code_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/sync_service_ids(.:format) */
export function alayacare_control_panel_sync_service_ids_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "sync_service_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/dedup_mrns(.:format) */
export function alayacare_control_panel_dedup_mrns_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "dedup_mrns" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/backfill_field_providers(.:format) */
export function alayacare_control_panel_backfill_field_providers_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "backfill_field_providers" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/sync_visit_types(.:format) */
export function alayacare_control_panel_sync_visit_types_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "sync_visit_types" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/clear_caches(.:format) */
export function alayacare_control_panel_clear_caches_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "clear_caches" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /alayacare_control_panel/backfill_visits(.:format) */
export function alayacare_control_panel_backfill_visits_path(options?: object): string {
  return "/" + "alayacare_control_panel" + "/" + "backfill_visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/index(.:format) */
export function athena_control_panel_index_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "index" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/sync_department_ids(.:format) */
export function athena_control_panel_sync_department_ids_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "sync_department_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/sync_cancel_code_ids(.:format) */
export function athena_control_panel_sync_cancel_code_ids_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "sync_cancel_code_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/sync_service_ids(.:format) */
export function athena_control_panel_sync_service_ids_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "sync_service_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/sync_visit_type_ids(.:format) */
export function athena_control_panel_sync_visit_type_ids_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "sync_visit_type_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/sync_custom_field_ids(.:format) */
export function athena_control_panel_sync_custom_field_ids_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "sync_custom_field_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/sync_field_provider_ids(.:format) */
export function athena_control_panel_sync_field_provider_ids_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "sync_field_provider_ids" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /athena_control_panel/initialize_regression_fixtures(.:format) */
export function athena_control_panel_initialize_regression_fixtures_path(options?: object): string {
  return "/" + "athena_control_panel" + "/" + "initialize_regression_fixtures" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** / */
export function root_path(options?: object): string {
  return "/" + $buildOptions(options, []);
}

/** /res */
export function ruby_event_store_browser_app_path(options?: object): string {
  return "/" + "res" + $buildOptions(options, []);
}

/** /flipper */
export function flipper_path(options?: object): string {
  return "/" + "flipper" + $buildOptions(options, []);
}

/** /delayed_job(.:format) */
export function delayed_job_path(options?: object): string {
  return "/" + "delayed_job" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /health(.:format) */
export function health_path(options?: object): string {
  return "/" + "health" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /jwt_web/scheduler/new(.:format) */
export function jwt_web_scheduler_new_path(options?: object): string {
  return "/" + "jwt_web" + "/" + "scheduler" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /jwt_web/scheduler/reschedule(.:format) */
export function jwt_web_scheduler_reschedule_path(options?: object): string {
  return "/" + "jwt_web" + "/" + "scheduler" + "/" + "reschedule" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/visits(.:format) */
export function api_v1_visits_path(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "visits" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/visits/new(.:format) */
export function new_api_v1_visit_path(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "visits" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /api/v1/visits/:id/edit(.:format) */
export function edit_api_v1_visit_path(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "visits" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/visits/:id(.:format) */
export function api_v1_visit_path(id: ScalarType, options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "visits" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /api/v1/visit_event(.:format) */
export function api_v1_visit_event_path(options?: object): string {
  return "/" + "api" + "/" + "v1" + "/" + "visit_event" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /inbound/lambdaforce(.:format) */
export function inbound_lambdaforce_path(options?: object): string {
  return "/" + "inbound" + "/" + "lambdaforce" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /lambdaforce/inbound(.:format) */
export function lambdaforce_inbound_path(options?: object): string {
  return "/" + "lambdaforce" + "/" + "inbound" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/action_mailbox/postmark/inbound_emails(.:format) */
export function rails_postmark_inbound_emails_path(options?: object): string {
  return "/" + "rails" + "/" + "action_mailbox" + "/" + "postmark" + "/" + "inbound_emails" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/action_mailbox/relay/inbound_emails(.:format) */
export function rails_relay_inbound_emails_path(options?: object): string {
  return "/" + "rails" + "/" + "action_mailbox" + "/" + "relay" + "/" + "inbound_emails" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/action_mailbox/sendgrid/inbound_emails(.:format) */
export function rails_sendgrid_inbound_emails_path(options?: object): string {
  return "/" + "rails" + "/" + "action_mailbox" + "/" + "sendgrid" + "/" + "inbound_emails" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/action_mailbox/mandrill/inbound_emails(.:format) */
export function rails_mandrill_inbound_health_check_path(options?: object): string {
  return "/" + "rails" + "/" + "action_mailbox" + "/" + "mandrill" + "/" + "inbound_emails" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/action_mailbox/mandrill/inbound_emails(.:format) */
export function rails_mandrill_inbound_emails_path(options?: object): string {
  return "/" + "rails" + "/" + "action_mailbox" + "/" + "mandrill" + "/" + "inbound_emails" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/action_mailbox/mailgun/inbound_emails/mime(.:format) */
export function rails_mailgun_inbound_emails_path(options?: object): string {
  return "/" + "rails" + "/" + "action_mailbox" + "/" + "mailgun" + "/" + "inbound_emails" + "/" + "mime" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/conductor/action_mailbox/inbound_emails(.:format) */
export function rails_conductor_inbound_emails_path(options?: object): string {
  return "/" + "rails" + "/" + "conductor" + "/" + "action_mailbox" + "/" + "inbound_emails" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/conductor/action_mailbox/inbound_emails/new(.:format) */
export function new_rails_conductor_inbound_email_path(options?: object): string {
  return "/" + "rails" + "/" + "conductor" + "/" + "action_mailbox" + "/" + "inbound_emails" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/conductor/action_mailbox/inbound_emails/:id/edit(.:format) */
export function edit_rails_conductor_inbound_email_path(id: ScalarType, options?: object): string {
  return "/" + "rails" + "/" + "conductor" + "/" + "action_mailbox" + "/" + "inbound_emails" + "/" + id + "/" + "edit" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /rails/conductor/action_mailbox/inbound_emails/:id(.:format) */
export function rails_conductor_inbound_email_path(id: ScalarType, options?: object): string {
  return "/" + "rails" + "/" + "conductor" + "/" + "action_mailbox" + "/" + "inbound_emails" + "/" + id + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["id","format"]);
}

/** /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format) */
export function new_rails_conductor_inbound_email_source_path(options?: object): string {
  return "/" + "rails" + "/" + "conductor" + "/" + "action_mailbox" + "/" + "inbound_emails" + "/" + "sources" + "/" + "new" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/conductor/action_mailbox/inbound_emails/sources(.:format) */
export function rails_conductor_inbound_email_sources_path(options?: object): string {
  return "/" + "rails" + "/" + "conductor" + "/" + "action_mailbox" + "/" + "inbound_emails" + "/" + "sources" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}

/** /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format) */
export function rails_conductor_inbound_email_reroute_path(inbound_email_id: ScalarType, options?: object): string {
  return "/" + "rails" + "/" + "conductor" + "/" + "action_mailbox" + "/" + inbound_email_id + "/" + "reroute" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["inbound_email_id","format"]);
}

/** /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format) */
export function rails_service_blob_path(signed_id: ScalarType, filename: ScalarType[], options?: object): string {
  return "/" + "rails" + "/" + "active_storage" + "/" + "blobs" + "/" + "redirect" + "/" + signed_id + "/" + filename.map((part) => $encode(part)).join("/") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["signed_id","filename","format"]);
}

/** /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format) */
export function rails_service_blob_proxy_path(signed_id: ScalarType, filename: ScalarType[], options?: object): string {
  return "/" + "rails" + "/" + "active_storage" + "/" + "blobs" + "/" + "proxy" + "/" + signed_id + "/" + filename.map((part) => $encode(part)).join("/") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["signed_id","filename","format"]);
}

/** /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) */
export function rails_blob_representation_path(signed_blob_id: ScalarType, variation_key: ScalarType, filename: ScalarType[], options?: object): string {
  return "/" + "rails" + "/" + "active_storage" + "/" + "representations" + "/" + "redirect" + "/" + signed_blob_id + "/" + variation_key + "/" + filename.map((part) => $encode(part)).join("/") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["signed_blob_id","variation_key","filename","format"]);
}

/** /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format) */
export function rails_blob_representation_proxy_path(signed_blob_id: ScalarType, variation_key: ScalarType, filename: ScalarType[], options?: object): string {
  return "/" + "rails" + "/" + "active_storage" + "/" + "representations" + "/" + "proxy" + "/" + signed_blob_id + "/" + variation_key + "/" + filename.map((part) => $encode(part)).join("/") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["signed_blob_id","variation_key","filename","format"]);
}

/** /rails/active_storage/disk/:encoded_key/*filename(.:format) */
export function rails_disk_service_path(encoded_key: ScalarType, filename: ScalarType[], options?: object): string {
  return "/" + "rails" + "/" + "active_storage" + "/" + "disk" + "/" + encoded_key + "/" + filename.map((part) => $encode(part)).join("/") + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["encoded_key","filename","format"]);
}

/** /rails/active_storage/disk/:encoded_token(.:format) */
export function update_rails_disk_service_path(encoded_token: ScalarType, options?: object): string {
  return "/" + "rails" + "/" + "active_storage" + "/" + "disk" + "/" + encoded_token + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["encoded_token","format"]);
}

/** /rails/active_storage/direct_uploads(.:format) */
export function rails_direct_uploads_path(options?: object): string {
  return "/" + "rails" + "/" + "active_storage" + "/" + "direct_uploads" + ($hasPresentOwnProperty(options, "format") ? "." + (options as any).format : "") + $buildOptions(options, ["format"]);
}
