# frozen_string_literal: true

## Note: if you are using the `directories` clause above and you are not
## watching the project directory ('.'), then you will want to move
## the Guardfile to a watched dir and symlink it back, e.g.
#
#  $ mkdir config
#  $ mv Guardfile config/
#  $ ln -s config/Guardfile .
#
# and, you'll have to watch "config/Guardfile" instead of "Guardfile"

to_rescue = ENV.key?("RESCUE_RSPEC") ? "rescue" : ""

pp "Rspec is running `bundle exec #{to_rescue} rspec`"

group :rails, halt_on_fail: true do
  guard :rspec, cmd: "bundle exec #{to_rescue} rspec", all_on_start: false, failed_mode: :keep do
    watch("spec/spec_helper.rb")                        { "spec" }
    watch("config/routes.rb")                           { "spec/routing" }
    watch("app/controllers/application_controller.rb")  { "spec/controllers" }
    watch(%r{^spec/.+_spec\.rb$})
    watch(%r{^app/(.+)\.rb$})                           {|m| "spec/#{m[1]}_spec.rb" }
    watch(%r{^app/(.*)(\.erb|\.haml|\.slim)$})          {|m| "spec/#{m[1]}#{m[2]}_spec.rb" }
    watch(%r{^lib/(.+)\.rb$})                           {|m| "spec/lib/#{m[1]}_spec.rb" }
    watch(%r{^app/controllers/(.+)_(controller)\.rb$})  do |m|
      ["spec/routing/#{m[1]}_routing_spec.rb", "spec/#{m[2]}s/#{m[1]}_#{m[2]}_spec.rb",
       "spec/acceptance/#{m[1]}_spec.rb"]
    end

    # Turnip features and steps
    watch(%r{^spec/acceptance/(.+)\.feature$})
    watch(%r{^spec/acceptance/steps/(.+)_steps\.rb$}) do |m|
      Dir[File.join("**/#{m[1]}.feature")][0] || "spec/acceptance"
    end
  end

  guard :rubocop, all_on_start: false, cli: ["--format", "clang", "--auto-correct"] do
    watch(%r{/.+\.rb$/})
    watch(%r{(?:.+/)?\.rubocop(?:_todo)?\.yml$}) {|m| File.dirname(m[0]) }
  end

  guard :brakeman, run_on_start: false, notifications: false do
    watch(%r{^app/.+\.(erb|haml|rhtml|rb)$})
    watch(%r{^config/.+\.rb$})
    watch(%r{^lib/.+\.rb$})
    watch("Gemfile")
  end
end
