if Rails.env.development?
  task generate_ts_routes: :environment do
    filename = Rails.root.join("app/javascript/src/common/routes.ts")
    source = [
      "/* THIS FILE IS AUTOMATICALLY GENERATED */",
      "/* RUN rake generate_ts_routes TO UPDATE THE ROUTES BELOW */",
      "",
      TsRoutes.generate(camel_case: false)
    ].join("\n")
    File.write(filename, source)
  end
end
